/*
 */
package view;

import javax.swing.JOptionPane;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane; 

/**
 *
 * @author a
 */
public class cadper extends javax.swing.JFrame {

    /**
     * Creates new form cadper
     */
    
    String url2 = "jdbc:mysql://localhost/perguntas"; // enderço do BD
  String username = "root";        //nome de um usuário de seu BD
  String password = "";  // senha do BD
  
    public cadper() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        perguntalabel = new javax.swing.JLabel();
        facil = new javax.swing.JRadioButton();
        medio = new javax.swing.JRadioButton();
        dificil = new javax.swing.JRadioButton();
        expert = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        perguntalabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        perguntalabel2 = new javax.swing.JLabel();
        perguntalabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        perguntalabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        perguntalabel5 = new javax.swing.JLabel();
        perguntalabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 43, 94));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<html><center>Voltar ao menu</center></html>");
        jButton1.setActionCommand("<html><center>Voltarao menu</center></html>");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 510, 140, 70);

        perguntalabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        perguntalabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perguntalabel.setText("<html><center><p style=color:white;width:100%;\">Alternativa 1:</p></center></html>");
        perguntalabel.setFocusable(false);
        perguntalabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(perguntalabel);
        perguntalabel.setBounds(140, 210, 170, 28);

        buttonGroup1.add(facil);
        facil.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        facil.setForeground(new java.awt.Color(255, 255, 255));
        facil.setSelected(true);
        facil.setText("Fácil");
        facil.setContentAreaFilled(false);
        facil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facilActionPerformed(evt);
            }
        });
        jPanel1.add(facil);
        facil.setBounds(180, 440, 90, 30);

        buttonGroup1.add(medio);
        medio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        medio.setForeground(new java.awt.Color(255, 255, 255));
        medio.setText("Médio");
        medio.setContentAreaFilled(false);
        jPanel1.add(medio);
        medio.setBounds(290, 440, 90, 30);

        buttonGroup1.add(dificil);
        dificil.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        dificil.setForeground(new java.awt.Color(255, 255, 255));
        dificil.setText("Difícil");
        dificil.setContentAreaFilled(false);
        jPanel1.add(dificil);
        dificil.setBounds(420, 440, 90, 30);

        buttonGroup1.add(expert);
        expert.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        expert.setForeground(new java.awt.Color(255, 255, 255));
        expert.setText("Expert");
        expert.setContentAreaFilled(false);
        jPanel1.add(expert);
        expert.setBounds(540, 440, 110, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 100, 360, 80);

        perguntalabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        perguntalabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perguntalabel1.setText("<html><center><p style=color:white;width:100%;\">Cadastro de perguntas</p></center></html>");
        perguntalabel1.setFocusable(false);
        perguntalabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(perguntalabel1);
        perguntalabel1.setBounds(0, 10, 800, 42);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<html>Cadastrar<br>pergunta</html>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(330, 510, 140, 70);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(460, 390, 90, 30);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(310, 210, 320, 28);

        perguntalabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        perguntalabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perguntalabel2.setText("<html><center><p style=color:white;width:100%;\">Pergunta:</p></center></html>");
        perguntalabel2.setFocusable(false);
        perguntalabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(perguntalabel2);
        perguntalabel2.setBounds(220, 60, 360, 28);

        perguntalabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        perguntalabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perguntalabel3.setText("<html><center><p style=color:white;width:100%;\">Alternativa 2:</p></center></html>");
        perguntalabel3.setFocusable(false);
        perguntalabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(perguntalabel3);
        perguntalabel3.setBounds(140, 250, 170, 28);

        jTextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(310, 250, 320, 28);

        perguntalabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        perguntalabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perguntalabel4.setText("<html><center><p style=color:white;width:100%;\">Alternativa 3:</p></center></html>");
        perguntalabel4.setFocusable(false);
        perguntalabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(perguntalabel4);
        perguntalabel4.setBounds(140, 290, 170, 28);

        jTextField3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(310, 290, 320, 28);

        jTextField4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(310, 330, 320, 28);

        perguntalabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        perguntalabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perguntalabel5.setText("<html><center><p style=color:white;width:100%;\">Alternativa correta:</p></center></html>");
        perguntalabel5.setFocusable(false);
        perguntalabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(perguntalabel5);
        perguntalabel5.setBounds(230, 390, 240, 28);

        perguntalabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        perguntalabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perguntalabel6.setText("<html><center><p style=color:white;width:100%;\">Alternativa 4:</p></center></html>");
        perguntalabel6.setFocusable(false);
        perguntalabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(perguntalabel6);
        perguntalabel6.setBounds(140, 330, 170, 28);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 600);

        setSize(new java.awt.Dimension(800, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void facilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facilActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Object certa = jComboBox1.getSelectedItem();
        String certav = (String) certa;
        String dificuldade = "";
        if (facil.isSelected()){
            dificuldade = "facil";
        } else if (medio.isSelected()){
            dificuldade = "medio";
        } else if (dificil.isSelected()){
            dificuldade = "dificil";
        } else if (expert.isSelected()){
            dificuldade = "expert";
        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecione uma dificuldade!");
        }
        
        String perguntav = jTextArea1.getText();
        String alt1 = jTextField1.getText();
        String alt2 = jTextField2.getText();
        String alt3 = jTextField3.getText();
        String alt4 = jTextField4.getText();
        
        controller.Driver.carregaDriver();
        

            Connection con = null;
                  
    try {
    con = (Connection) DriverManager.getConnection(url2, username, password);
    } catch (SQLException ex) {

    Logger.getLogger(cadper.class.getName()).log(Level.SEVERE, null, ex);

            
                   }

            // Recebendo os dados a serem inseridos na tabela
            String sql = "INSERT INTO " + dificuldade + "(pergunta, resp1, resp2, resp3, resp4, cor) values('" + perguntav + "','"+alt1+"','"+alt2+"','"+alt3+"','"+ alt4 + "','" + certav + "')";
     
            try { // Tratamento de Erros para inserção

                // Criando varialvel que executara a inserção
                PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção

  JOptionPane.showMessageDialog(null,"<html><h1 style='color:green;'>Pergunta cadastrada com sucesso!</h1></html>","Pergunta cadastrada!",-1);
                jTextArea1.setText("");
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                facil.setSelected(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Erro na inserção!","ERRO!",0);
            }     

        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton dificil;
    private javax.swing.JRadioButton expert;
    private javax.swing.JRadioButton facil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JRadioButton medio;
    private javax.swing.JLabel perguntalabel;
    private javax.swing.JLabel perguntalabel1;
    private javax.swing.JLabel perguntalabel2;
    private javax.swing.JLabel perguntalabel3;
    private javax.swing.JLabel perguntalabel4;
    private javax.swing.JLabel perguntalabel5;
    private javax.swing.JLabel perguntalabel6;
    // End of variables declaration//GEN-END:variables
}
